font_family      JetBrainsMono Nerd Font ExtraBold
font_size        15.0
modify_font      line_height 110%

enabled_layouts splits,stack

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

map cmd+d launch --location=vsplit --cwd=current
map cmd+shift+d launch --location=hsplit --cwd=current

map cmd+w close_window

map cmd+z toggle_layout stack

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

hide_window_decorations titlebar-only
window_padding_width 5
copy_on_select yes
include ./theme.conf

active_border_color #0969da
inactive_border_color #d0d7de
window_border_width 1pt

tab_bar_style fade
active_tab_foreground   #24292f
active_tab_background   #ffffff
active_tab_font_style   bold
inactive_tab_foreground #57606a
inactive_tab_background #f6f8fa
tab_bar_background      #f6f8fa
map alt+f toggle_fullscreen
