set nocompatible
filetype plugin indent on
syntax on

set termguicolors
set background=light
colorscheme mono
set listchars+=tab:»\ ,trail:·,extends:›,precedes:‹
set fillchars=fold:\ ,foldopen:\ ,foldclose:\ ,diff:-

set backspace=indent,eol,start
set hidden
set number
set relativenumber
set cursorline

set autoindent
set nowrap
set scrolloff=5
set splitright
set splitbelow
set tabstop=4
set shiftwidth=4
set expandtab
set hlsearch
set incsearch
set path+=**
set mouse=a

set wildmenu
set wildignorecase
set wildignore=*.o,*.obj,*.a,*.so,*.d

let mapleader=" "
set timeoutlen=400

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

nnoremap <C-S-h> <C-w>H
nnoremap <C-S-j> <C-w>J
nnoremap <C-S-k> <C-w>K
nnoremap <C-S-l> <C-w>L

nnoremap <leader>ff :find <Tab>
nnoremap <leader>fg :grep <C-r><C-w><CR>
nnoremap <leader>sg :vimgrep /<C-r><C-w>/j .<CR>
nnoremap <leader>fe :Lexplore<CR>
nnoremap <leader>e  :Lexplore<CR>
nnoremap <leader>E  :Lexplore <C-r>=expand('%:p:h')<CR><CR>
nnoremap <C-s> :w<CR>
nnoremap <leader>w  :w<CR>
nnoremap <leader>q  :q<CR>
nnoremap <leader>qa :qa<CR>
nnoremap <leader>qq :qa<CR>

nnoremap <leader>b  :b#<CR>
nnoremap <leader>bp :b#<CR>
nnoremap <leader>bl :buffers<CR>
nnoremap <leader>bd :bd<CR>

nnoremap <leader>m  :make<CR>
nnoremap <leader>cc :!clear && gcc -Wall -Wextra %:p -o /tmp/vimrun && /tmp/vimrun<CR>
nnoremap <leader>r  :!clear && /tmp/vimrun<CR>

nnoremap <leader>n  :cnext<CR>
nnoremap <leader>p  :cprev<CR>
nnoremap <leader>cd :copen<CR>
nnoremap <leader>cq :cclose<CR>
nnoremap <leader>us :set spell<CR>

nnoremap <C-]> g<C-]>
nnoremap <leader>t <C-t>

nnoremap <leader><Space> :nohlsearch<CR>

cnoreabbrev w!! w !sudo tee > /dev/null %

autocmd BufWritePre * :%s/\s\+$//e

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_winsize = 25
let g:netrw_altv = 1
let g:netrw_fastbrowse = 2
let g:netrw_sort_sequence = '[\/]$,*'
autocmd FileType netrw setl bufhidden=delete

set cindent
set cinoptions+=t0,g0,N-s

function! ShowCheat()
  if bufloaded('vim-cheat') | execute 'buffer vim-cheat' | return | endif
  vnew vim-cheat
  setlocal buftype=nofile bufhidden=wipe nobuflisted noswapfile
  setlocal nonumber norelativenumber cursorline
  nnoremap <buffer> q :bdelete<CR>
  let lines = [
      \ '',
      \ '  VIM  C/C++  CONFIG          (leader = пробел, как в nvim)',
      \ '  ' . repeat('=', 52),
      \ '',
      \ '  ff  открыть файл по имени     fg  grep по слову под курсором',
      \ '  sg  vimgrep по слову            e   explorer  on/off',
      \ '  fe  explorer                    E   explorer в текущей папке',
      \ '  w   сохранить (и Ctrl+s)        q   выйти',
      \ '  b   предыдущий буфер             bl  список буферов',
      \ '  bd  закрыть буфер               qq  выйти из всех',
      \ '',
      \ '  m   make                       cc  gcc compile + run',
      \ '  r   rerun                      n / p  след./пред. ошибка',
      \ '  cd  ошибки (copen)            cq  закрыть список ошибок',
      \ '  us  spell',
      \ '',
      \ '  Space Space  убрать подсветку  t   назад по тегам',
      \ '  Ctrl+]  к определению',
      \ '',
      \ '  Ctrl+h/j/k/l    окна          Ctrl+Shift+h/j/k/l  окна во весь экран',
      \ '',
      \ '  h  эта справка   ?  тоже      q  закрыть её',
      \ '  полная шпаргалка: ~/.config/HOTKEYS.md',
      \ ]
  call setline(1, lines)
  setlocal nomodifiable nomodified
  normal G
endfunction
nnoremap <leader>h  :call ShowCheat()<CR>
nnoremap <leader>?  :call ShowCheat()<CR>
autocmd VimEnter * if argc()==0 | call ShowCheat() | endif
